apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubemq.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: api-port
    port: {{ .Values.service.apiPort }}
    protocol: TCP
    targetPort: {{ .Values.env.apiPort }}
  - name: grpc-port
    port: {{ .Values.service.grpcPort }}
    protocol: TCP
    targetPort: {{ .Values.env.grpcPort }}
  - name: rest-port
    port: {{ .Values.service.restPort }}
    protocol: TCP
    targetPort: {{ .Values.env.restPort }}
  - name: cluster-port
    port: {{ .Values.service.clusterPort }}
    protocol: TCP
    targetPort: {{ .Values.env.clusterPort }}
  sessionAffinity: None
  selector:
    app: {{ include "kubemq.name" . }}
